name: ClawChain Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - run: npm run build
    - run: npm test
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js  
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
    - name: Deploy to production
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        ssh $SSH_USER@$SSH_HOST 'cd /path/to/clawchain && git pull && npm install && npm run build && pm2 restart backend'