name: ClawChain CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  backend:
    uses: ./.github/workflows/backend.yml
    
  frontend:
    uses: ./.github/workflows/frontend.yml
    
  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to production
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        ssh $SSH_USER@$SSH_HOST 'cd /path/to/clawchain && docker-compose up -d'