name: Deploy

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build
    - name: Deploy to production
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        KEY: ${{ secrets.SSH_KEY }}
      run: |
        ssh $USER@$HOST 'mkdir -p /var/www/clawchain'
        scp -r backend frontend $USER@$HOST:/var/www/clawchain/
        ssh $USER@$HOST 'cd /var/www/clawchain && npm install && pm2 restart clawchain'